server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: smartshop

  datasource:
    url: jdbc:postgresql://localhost:5432/smartshop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0123456789

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
